### ISSUE TITLE
Clarify whether a dictionary member set to `undefined` is "present"

### ISSUE THREAD

**Issue by ddorwin** [heycam/webidl#124]
https://heycam.github.io/webidl/#dfn-present says, "When specified in the dictionary value, a dictionary member is said to be present, otherwise it is not present."

It is not immediately clear whether a value set to `undefined` should be considered "specified in the dictionary value" and thus present. The same issue may apply for `null`.

It appears (i.e. https://github.com/w3c/encrypted-media/issues/178#issuecomment-216124376) at least some implementations may consider `dictionaryValue:undefined` to be *not* specified while actually tracking the presence of the value (i.e. in dev tools).

**Comment by bzbarsky** [comment]
> It is not immediately clear whether a value set to undefined should be considered "specified in the dictionary value" and thus present. 

It follows directly from http://heycam.github.io/webidl/#es-to-dictionary step 5 substep 1 subsubstep 3.  `undefined` is treated the same way as a missing property (as it has to be, because step 5 substep 1 subsubstep 2, which just does [[Get]]).

The section you link to is in the language-agnostic section of the spec, so can't talk about interactions with the ES `undefined` value.

> The same issue may apply for null

`null` is not magic.  It gets converted to the type specified for the dictionary member in the usual way (this may of course throw).

> at least some implementations may consider dictionaryValue:undefined to be not specified

I'd hope they all do!  The spec is really clear on this and has been for years.

Devtools can obviously do whatever they want.

**Comment by ddorwin** [comment]
Thank you.
