### ISSUE TITLE
Does a non-nullable and non-required dictionary member of interface type make sense?

### ISSUE THREAD

**Issue by foolip** [heycam/webidl#176]
Context: https://github.com/WebAudio/web-audio-api/issues/980

Let's simplify:

```WebIDL
dictionary Foo {
  EventTarget target;
};
```

The only difference to making it nullable is that `{target: null}` would throw TypeError, might one want that?

Or: should WebIDL require (hah) that required dictionary members are non-nullable and that optional ones are nullable? And have a default value of null, so that omitting can't have another meaning?

(Sorry if the spec already has some requirements like this, it's big.)

**Comment by annevk** [comment]
I think throwing for null (or stringifying null for DOMString) is what we want here. Use undefined for omission. We have moved away from treating them equivalent.

**Comment by foolip** [comment]
I'm not suggesting that null be treated as missing for dictionary members, not even for interface types, but I do wonder if WebIDL can do more to help spec writers figure out when to use the above `dictionary Foo` as opposed to this:

```WebIDL
dictionary Foo {
  EventTarget? target = null;
};
```

I looked in Blink for optional, non-nullable members of interface type, and the only two cases were mistakes:
https://github.com/WebAudio/web-audio-api/issues/980
https://github.com/WebAudio/web-audio-api/issues/985

So, I'm tentatively arguing that for dictionary members of interface type, they must nullable if optional and not nullable if required, and wonder if that's overlooking something.

**Comment by domenic** [comment]
No, we want to make `foo({ target: null })` throw, and `foo({ target: undefined })` or `foo({ })` work. Thus we want to **discourage**

```webidl
dictionary Foo {
  EventTarget? target = null;
};
```

in favor of

```webidl
dictionary Foo {
  EventTarget target;
};
```

**Comment by foolip** [comment]
@domenic, can you find an example of an API you think should have used a non-nullable but optional type? These are the dictionaries that have such members in Blink:
* ConvolverOptions
* DragEventInit
* FocusEventInit
* GamepadEventInit
* HitRegionOptions
* InputEventInit
* IntersectionObserverInit
* MediaEncryptedEventInit
* MediaKeyMessageEventInit
* MediaStreamEventInit
* MessageEventInit
* MIDIConnectionEventInit
* MIDIMessageEventInit
* MouseEventInit
* OscillatorOptions
* RelatedEventInit
* SensorReadingEventInit
* SpeechRecognitionEventInit
* StorageEventInit
* UIEventInit
* USBConnectionEventInit
* VRDisplayEventInit
* VRLayer

**Comment by foolip** [comment]
A few of those have ongoing spec issues:
https://github.com/WebAudio/web-audio-api/issues/980
https://github.com/w3c/encrypted-media/issues/329
https://github.com/w3c/webvr/issues/89

And a few are just Blink's IDL being wrong, will edit previous comment.

**Comment by domenic** [comment]
I guess this is one of those "be consistent with the old, slightly bad thing" vs. "be inconsistent and adopt the better thing". There are a lot of old dictionaries that use nullable, whereas it would be nicer if undefined was the only defaulter on the platform. (For consistency with ES, and with optional arguments, among others.)

I'm inclined to say that going forward we should not use nullable in this way, but I could be persuaded to be consistent with the old, slightly bad thing.

**Comment by foolip** [comment]
Can you give an instance of the existing ones that you think was a mistake? (Previous comment edited.)

**Comment by bzbarsky** [comment]
One can make the argument for accepting null if the intent of the argument is to pass in a thing that will get stored and returned later.  This allows the thing that gets passed in to be exactly the thing that's stored, and in the particular case of a constructor argument options object may allow an existing object to be used as the options object.  Of course in the case of `AudioBufferSourceNode` in particular that won't work because `detune` and `playbackRate` have different types in the object and the dictionary...  

Anyway, the event init dictionaries by and large follow the above pattern of using null in the dictionary when it's passing through a value that will then get stored in an internal slot on the event and returned from a getter directly.  That covers most of the dictionaries in https://github.com/heycam/webidl/issues/176#issuecomment-248259867

I think HitRegionOptions should not have used a nullable thing, probably.

(Of course one could make the argument that the "stored and returned later" case should _return_ undefined instead of null when there is nothing stored...)

**Comment by foolip** [comment]
Right, HitRegionOptions is the only remaining thing on my list that isn't an init dict. Would the API really have been better if `context.addHitRegion({ id: "foo", control: null })` threw TypeError?

As part of https://crbug.com/647693 I had to look at all option, non-nullable dictionary members of interface type, and without exception they should either be required or made nullable, see spec issues linked in https://github.com/heycam/webidl/issues/176#issuecomment-248259867. So my selfish motivation here is that if webidl2.js and Blink's IDL parser would complain about cases like with, I won't have to spend time on these things again.

**Comment by annevk** [comment]
`HitRegionOptions` is a good example, it's inconsistent. Since you get "null" for id when passing null, you'd expect it to throw for control since no type coercion can be applied there.

**Comment by foolip** [comment]
From "no type coercion can be applied" I wonder if you overlooked that `control` is already nullable? The question is if it would have been better if non-nullable?

I'd argue that making these things nullable will always be harmless, consistent with everything that already exists, and help catch mistakes where it wasn't intentional.

**Comment by annevk** [comment]
Yeah, I think it would be better to match the signature of the id member.

The fact is that JavaScript special cases undefined, but not null. So wherever we treat null as undefined or the empty string, rather than a disallowed value and "null", we're being inconsistent with JavaScript.

As mentioned upthread there are sometimes good reasons to allow null, but I don't think this is it.

**Comment by foolip** [comment]
Interesting, here's a case with prose using something other than null as the default:
https://wicg.github.io/IntersectionObserver/#dictdef-intersectionobserverinit

**Comment by foolip** [comment]
Closing this issue, I think I'll be skeptical if an API comes out with an optional but not nullable member of interface type, but we can fight that battle then.

**Comment by annevk** [comment]
RequestInit does that for headers...

**Comment by foolip** [comment]
Looks like Blink's RequestInit doesn't use an IDL dictionary but some custom handling, so it didn't show up. But because HeadersInit is a union type that includes a dictionary type, null will presumably be treated as that dictionary per https://heycam.github.io/webidl/#es-union?
