### ISSUE TITLE
Use OrdinarySet instead of [[Set]]

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#201]
Last step of the algorithm "to invoke the internal [[Set]] method of platform objects" in [Platform object [[Set]] method](https://heycam.github.io/webidl/#platformobjectset) instructs to perform steps 3-11 of the [default [[Set]] internal method](https://tc39.github.io/ecma262/#sec-ordinary-object-internal-methods-and-internal-slots-set-p-v-receiver), when it should instead rely on [OrdinarySet](https://tc39.github.io/ecma262/#sec-ordinaryset).

It might be possible to rework the algorithm to avoid plugging into the middle of the algorithm, which is always brittle.

Also, remove |ownDesc| from Ignored Vars.

**Comment by annevk** [comment]
Yeah, wherever we do that we should refactor. We can also request changes to ECMAScript if needed.

**Comment by bzbarsky** [comment]
> when it should instead rely on OrdinarySet.

It can't rely on `OrdinarySet`, precisely because step 2 of `OrdinarySet` is wrong for this use case.  Where "wrong" means "not web-compatible".  Also, note that `OrdinarySet` is just a spec algorithm, not the name of an abstract operation, so there is no such thing as `[[OrdinarySet]]`.  

I agree it would be nice if ES had a hook we could just use here, since the reference is _already_ broken due to their refactoring.  I thought I had discussed this with them when we were adding this and they planned to at least let us know they broke the ref, but I may well be misremembering...  :(

**Comment by domenic** [comment]
We should get ES updated to have something we can use.

**Comment by tobie** [comment]
> It can't rely on OrdinarySet, precisely because step 2 of OrdinarySet is wrong for this use case. Where "wrong" means "not web-compatible".

Understood. I meant to say we should:

1. change the algorithm to refer to steps 3-n of the OrdinarySet algorithm instead of [[Set]], as the latter only has a single step, and
2. get a proper hook in the OrdinarySet algorithm.

> Also, note that OrdinarySet is just a spec algorithm, not the name of an abstract operation, so there is no such thing as [[OrdinarySet]].

Fixed the title. Thanks.

**Comment by annevk** [comment]
@bzbarsky note that before you blame an ominous "them", the refactoring to ES was done by me to get `WindowProxy` / `Location` properly defined. "They" might have forgotten about this dependency or thought I knew about that.

Also, could we not fix this by having a flag that our custom [[GetOwnProperty]] uses?

**Comment by bzbarsky** [comment]
> note that OrdinarySet is just a spec algorithm, not the name of an abstract operation

Correction: it _is_ an abstract operation but it's not an internal method.  The latter are what get the [[]] naming.

> before you blame an ominous "them"

Not blaming anyone except myself.  If there wasn't a comment in the ES spec source about needing to be careful with [[Set]] to avoid breaking IDL, then I clearly didn't communicate things clearly enough.

> could we not fix this by having a flag that our custom [[GetOwnProperty]] uses?

You mean a "called from [[Set]]" flag that gets passed as an argument?  Or something else?

**Comment by annevk** [comment]
Our [[Set]] sets an internal slot on the platform object before invoking OrdinarySet and afterwards unsets it. Our [[GetOwnPropery]] uses that internal slot to avoid returning the wrong thing.

**Comment by bzbarsky** [comment]
> Our [[Set]] sets an internal slot on the platform object 

It's complicated, because you can get lots of calls to [[GetOwnProperty]] under the [[Set]] call (and in fact can run arbitrary amounts of script under there), but we only want to affect the one specific [[GetOwnProperty]] that looks up that one property at the beginning of OrdinarySet.

We could set the flag in our [[Set]] and then have the very first [[GetOwnProperty]] call unset the flag before carrying on.  But now we're making assumptions about the internals of the default [[Set]] or OrdinarySet and what internal methods it invokes in which order...

**Comment by annevk** [comment]
Ah yes, filed https://github.com/tc39/ecma262/issues/719.

**Comment by samweinig** [comment]
While waiting for a hook to be defined, is there a short term fix we can put in to WebIDL, perhaps referencing some subset of the OrdinarySet abstract algorithm (steps x to y)?

**Comment by bzbarsky** [comment]
We do that already, though the language predates OrdinarySet existing as a thing distinct from https://tc39.github.io/ecma262/#sec-ordinary-object-internal-methods-and-internal-slots-set-p-v-receiver

Specifically, WebIDL right now says "Perform steps 3-11 of the default [[Set]] internal method".  We could certainly change that to "Perform steps 3-11 of OrdinarySet" and change where the link points to...

**Comment by Ms2ger** [comment]
OrdinarySetWithOwnDescriptor() now exists.

**Comment by annevk** [comment]
All thanks to @TimothyGu! \o/
