### ISSUE TITLE
[Clamp] and [EnforceRange] reduce the max value long long supports

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#237]
[`long long`](https://heycam.github.io/webidl/#es-long-long) and [`unsigned long long`](https://heycam.github.io/webidl/#es-unsigned-long-long) behave differently when used in conjunction with [Clamp] or [EnforceRange]. In that case the max supported value is 2^53 – 1. When used without extended attributes, it's 2^64.

Particularly relevant are steps 2.3, 3.1 and 6 of both algorithms.

**Comment by tobie** [comment]
@bzbarsky, any idea what's going on here?

**Comment by bzbarsky** [comment]
The 2^53-1 comes from https://www.w3.org/Bugs/Public/show_bug.cgi?id=24241

Is the question why the normal case doesn't take things mod 2^53 as well?  Mostly because that's a pretty nonsensical thing to do and is more datalossy than taking things mode 2^64.  The dataloss is not a problem in the enforcerange/clamp cases because those don't have silent dataloss at all, right?

**Comment by tobie** [comment]
If by silent you mean doesn't not throw at runtime, then clamping is silent.

**Comment by domenic** [comment]
I wonder why the normal case takes things mod 2^64 at all :-/. I guess because the name, `long long`, is reminiscent of int64 in some platforms, but it seems like a shame there's no "don't modulo me" integer type.

**Comment by bzbarsky** [comment]
By "silent" I mean "not obvious to the spec writer".  Clamping is very explicitly throwing away data, and knows it's doing it.

> I wonder why the normal case takes things mod 2^64 at all

Because that's the simple thing to do when you convert a double to a 64-bit integer in C/C++, is the honest explanation.  ;)  So that's what browsers did, etc.

> but it seems like a shame there's no "don't modulo me" integer type.

We're talking bigint here, right?  There seem to be no real use cases, and implementing such things in a non-performance-sucky way is not trivial, so....

**Comment by domenic** [comment]
Well, or just double, but I guess at some point internal to the browser code you'll need to start working with C++ integer types, and then we run into the same issue. Yeah, I guess this all makes sense.

**Comment by bzbarsky** [comment]
Right, if you want just double, you spec it as "double" and there is no issue.
