### ISSUE TITLE
Remove [LegacyArrayClass]

### ISSUE THREAD

**Issue by annevk** [heycam/webidl#291]
I thought I had raised this before but I cannot find it. I don't see a reason to keep this prototype-changing thingy around. Interfaces that need it should be able to use `iterable<>` instead and since it's relatively new it seems unlikely this is fully interoperable anyway.

On IRC someone mentioned CSSOM uses this. @zcorpan, do you think that usage can be replaced with `iterable<>`?

**Comment by domenic** [comment]
This would be a big web-breaking change as such classes would lose all their Array methods (map, filter, etc.).

What interfaces on the platform currently use LegacyArrayClass?

**Comment by annevk** [comment]
@zcorpan all `[LegacyArrayClass]` does is that it puts `Array.prototype` on the prototype chain. It is unrelated to `item()`.

https://drafts.csswg.org/cssom/ says `MediaList`, `StyleSheetList`, and `CSSRuleList` use it.

`w("map" in document.styleSheets)` returns false in every browser I tried it in...

**Comment by Ms2ger** [comment]
Gecko has it on `MediaList` (since Fx28) and `DOMRectList`. See <http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4850> for example.

**Comment by annevk** [comment]
That yields undefined in Chrome and Safari.

**Comment by zcorpan** [comment]
I meant in reply to "do you think that usage can be replaced with `iterable<>`?" -- the problem with that is `item()` disappears, AIUI. So we can't do that unless usage of `item()` is low enough that we can break it.

**Comment by bzbarsky** [comment]
> the problem with that is item() disappears

Why would that be the case?  I don't think it would be...

**Comment by zcorpan** [comment]
Oh, OK, then it is probably fine. (Maybe I was thinking of `sequence<>`...)

**Comment by tabatkins** [comment]
CSS Typed OM would like to use [LegacyArrayClass], or something similar to it, to represent a list of transform functions.  We're currently using iterable, but that means that to do anything useful with the value, you have to first cast it to an array, and then cast it back.

**Comment by annevk** [comment]
Why can't you have a getter that returns a new (actual) array representing the functions?

**Comment by tabatkins** [comment]
That's equivalent to doing an array cast (`el.toArray().map()` vs `[...el].map()`). It's just one more step that people have to do to use the value "normally".  This was bad when querySelectorAll() did it, and it's bad here, too.

Maplikes/setlikes get the full suite of Map/Set functions automatically; you don't need to cast them into a Map/Set to use them.  People very often want to map/forEach/etc a sequence-ish value.  I know that getting `a[0]` to work on an array-like is out of the question right now (grr), but we can do everything else with fairly minimal pain.

**Comment by bzbarsky** [comment]
`a[0]` will work just fine for things with indexed getters, right?

`forEach` will work for anything with an iterable declaration, including a thing with an indexed getter and a value iterable decl.

But yes, the lack of `map()` is just kinda silly.  On the other hand, the lack of `reverse()` is not necessarily silly...

Anyway, without having seen your use cases, it seems like generally we have a few options:

1. Just accept that we have some [ArrayClass] things.  That requires an indexed getter and an optional indexed setter if you want the mutation functions to work.  The latter might require a writable "length" too.
2. Explicitly give more things the `forEach` treatment.  The list of plausible candidates here probably includes all the non-mutating functions on Array.prototype: `includes`, `indexOf`, `lastIndexOf`, `find`, `filter` (but what sort of object should this return?), `map` (again, what should this return?), `reduce`, `reduceRight`, `some`.  We already have `forEach`, `keys`, `values`, `@@iterator`.  This all still involves indexed props.
3. Do actual Array subclasses.  This has the drawback of it probably being a bit more pain to write specs in terms of these, and it not being clear to me what the readonly story is, if anything.  It has the benefit that all the stuff on Array will work.

maplike/setlike were a much easier problem, because Map/Set they only admit mutation via methods, so doing a readonly thing is easy: just leave out those methods....

**Comment by tabatkins** [comment]
> `a[0]` will work just fine for things with indexed getters, right?

It "works fine" by requiring a proxy to intercept all numeric property accesses, because TC39 hasn't gotten its head out of its ass and added a hook for [] syntax yet. :(  As such, it's not a solution we want to use in general.

> But yes, the lack of map() is just kinda silly. On the other hand, the lack of reverse() is not necessarily silly...

My use-case is dead lists, so there's nothing wrong with .reverse() or any of the other this-mutating functions.  But yeah, if we wanted to do this "properly", you'd want to separate out the list of mutating functions.

> filter (but what sort of object should this return?), map (again, what should this return?), 

Easy to define that the auto-defined versions of these methods return values of the same type, but I guess the problem is live collections, where it's not clear what the effect of such a thing would be?

I bet we could hinge it on whether there exists a constructor that takes a single `sequence<>` argument: if so, those methods automatically cast the result back into the type; if not, you get an Array back.  If you want an Array all the time, you can cast it yourself.

Or make it more explicit, with a variant `iterator` declaration that says whether the collection is live or dead.  (Maybe `arraylike<>` for the dead version?) And then require that `arraylike<>`s have an appropriate constructor to be valid.

**Comment by annevk** [comment]
What is a dead list?

**Comment by tabatkins** [comment]
One that's not live?  If you modify it, nothing happens beyond the mutation to the one object you're holding, and the system won't modify it underneath you.

**Comment by annevk** [comment]
That sounds good. In that case you really want to use an array subclass I think (or just an array if you don't need anything else on it).

**Comment by tabatkins** [comment]
I agree, which is why I want to use `[LegacyArrayClass]`, or something similar to it, and we shouldn't remove it unless there's a better option. ^_^

**Comment by annevk** [comment]
`[LegacyArrayClass]` is not the way to get a proper subclass though. Subclassing arrays is https://www.w3.org/Bugs/Public/show_bug.cgi?id=20020 though that hasn't really gone anywhere yet unfortunately.

**Comment by tabatkins** [comment]
Tho *just* using an Array subclass still leaves you with the question, raised by Boris, of what the result of calling `obj.map()` is; if this is grabbing the `Array.prototype.map` function, then your callback result isn't typechecked, and the method returns an ordinary Array.  (Same with `filter`, and any of the other Array methods that return an Array.)  Ideally you want the result to be an object of the same type.

**Comment by tabatkins** [comment]
In other words, I think it's better to lean towards the `maplike` solution, where copycat versions of the Array methods get auto-defined for your interface that give the right behavior. WebIDL can update itself as JS adds new methods to Array.

This means that adding to Array.prototype doesn't make them work on your object, but that's already how `maplike<>` and `setlike<>` work, so we're at least consistent. (And when JS finally defines the `::` operator, fake additions to Array will work just fine on arraylikes as well.)

**Comment by bzbarsky** [comment]
> It "works fine" by requiring a proxy to intercept all numeric property accesses

Well.... on a conceptual spec level, true.  Engines _can_ optimize things to have an internal hook like the one you describe if they want to.  That said, the various issues with it that I think people object to would be the same with such a hook.

> As such, it's not a solution we want to use in general.

What are the specific concerns with using it, other than "makes the spec author feel icky"?

> My use-case is dead lists

Dead in the sense that you set it up, hand it to someone, and never look at it again?

In that case, why not just use Arrays or an Array subclass (ignoring for the moment the lack of easy way to express it in IDL)?  I feel like I'm missing something...

> Easy to define that the auto-defined versions of these methods return values of the same type

That doesn't necessarily make sense for map, note.  If you have a list of Foo objects and call map on it with a function that returns booleans, you get a list of booleans.  Whether it makes sense to still represent it by the same list type kinda depends on what operations are defined for your list.  Not an issue for filter(), of course.

> but I guess the problem is live collections

Sure.  We could do the map() thing as an opt-in via some IDL syntax and only non-live collections would define it.  Or one of your suggestions.

> Tho just using an Array subclass still leaves you with the question, raised by Boris, of what the result of calling obj.map() is

Right, you have to define it.

> if this is grabbing the Array.prototype.map function, then your callback result isn't typechecked, and the method returns an ordinary Array

Not quite.  You're right that the callback result is not typechecked.  What it returns depends on your .constructor value and its Symbol.species property, etc.

That is, ES `Array.prototype.map` can return an object with the proto chain the "this" value chooses, but it's still a JS array and anyone can stick anything into it, just like any Array subclass instance.

> Same with filter, and any of the other Array methods that return an Array.

`filter` is simpler, again because it uses existing values, so won't mess up your element types for you.  The created thing again depends on your .constructor and whatnot.  See https://tc39.github.io/ecma262/#sec-array.prototype.filter step 5 and the https://tc39.github.io/ecma262/#sec-arrayspeciescreate rabbit hole.

**Comment by tabatkins** [comment]
> What are the specific concerns with using it, other than "makes the spec author feel icky"?

Ask @annevk, he's the one that keeps throwing shade at me whenever I suggest doing that.

> In that case, why not just use Arrays or an Array subclass (ignoring for the moment the lack of easy way to express it in IDL)? I feel like I'm missing something...

A straight Array subclass means you'll return a straight Array from any of the methods that return an array.

> That doesn't necessarily make sense for map, note. If you have a list of Foo objects and call map on it with a function that returns booleans, you get a list of booleans. Whether it makes sense to still represent it by the same list type kinda depends on what operations are defined for your list.

Sure, but we have an easy way to indicate that you want a sequence container capable of holding any value - cast it to an array.  If you're operating on a specialized object, you should play by the specialized object's rules.  That way, you'll still have access to the specialized object's other methods.

> See https://tc39.github.io/ecma262/#sec-array.prototype.filter step 5 and the https://tc39.github.io/ecma262/#sec-arrayspeciescreate rabbit hole.

Oh, I didn't realize that it was subclass-friendly now!  In that case, with some IDL indication, we could just say that the object should advertise itself as its species.  So yeah, we could just do an Array subclass, I guess.

**Comment by annevk** [comment]
Folks from TC39 have repeatedly asked us to stop designing APIs that require proxies. We could maybe have another discussion with them if we have a set of use cases and figure out what is best.

> A straight Array subclass means you'll return a straight Array from any of the methods that return an array.

Is that true? https://tc39.github.io/ecma262/#sec-array.prototype.map suggests you get an instance of the subclass. Anyway, I don't see how `[LegacyArrayClass]` helps with this.

**Comment by tabatkins** [comment]
> Folks from TC39 have repeatedly asked us to stop designing APIs that require proxies.

Tho, it looks like using `iterable<>` automatically opts you into needing proxies, because you're required to support indexed properties for it, and that gives you the `a[0]` support.  Right?  So there's no way to make anything even *remotely* Array-like without making a Proxy in WebIDL?

> Is that true?

Yeah, bz points out that it's not, as I recognized in the later part of my response. ^_^

> Anyway, I don't see how [LegacyArrayClass] helps with this.

I mean, [LegacyArrayClass] is basically "subclassing Array".  All "subclass" means is that the superclass's prototype is in the subclass's prototype chain.  Am I drastically misunderstanding something here?

**Comment by domenic** [comment]
Subclassing is indeed very different from just prototype linkage. It means inheriting the allocation behavior of array, e.g. its magic length property and Array.isArray working.

**Comment by tabatkins** [comment]
Oh jeez, I thought the magic inherited there, but now that I think about it, whenever I've done this in the past, my "constructor" just decorated an Array and returned it. ^_^

**Comment by annevk** [comment]
@tabatkins an iterable that is a value iterator rather than a pair iterator does so indeed. My recollection is that we only added that for legacy classes that we could not convert to arrays or subclasses of arrays.

(I have filed bugs to make it clearer in IDL what is recommended and what is not, but there's a huge backlog...)

**Comment by tabatkins** [comment]
So it looks like the best solution for me, right now, is to instead declare that this is a pair iterator whose "key" is just the index.  That gives the behavior that I actually want, because the value iterator is broken. :(

This is, obviously, dumb as hell.

**Comment by annevk** [comment]
Why not make array subclassing work?

**Comment by tabatkins** [comment]
Because I'm not the WebIDL editor, I'm not familiar with the problems that made it hard previously, nor do I have the experience to navigate what is probably a pretty complicated topic (hooking into the ES spec properly).

I'm just trying to write a spec that *uses* WebIDL here.

**Comment by annevk** [comment]
I think the main thing that had been blocking it thus far is lack of the feature in implementations. I think that has been resolved. Going with a hack instead of doing the proper thing because you don't think it's your responsibility does seem like a problem of sorts. You could just any meanwhile.

I believe we previously came up with the requirement that the API should be good JavaScript and either IDL enables that or you need to just do it yourself and get IDL fixed (either later or right away).

**Comment by tabatkins** [comment]
Right; my suggestion was not *seriously* that I use a pair iterator, just that using a pair iterator is the best current solution to my problem; it does exactly what I want (at least, the minimal form of "what I want"), and what value iterators apparently *originally* did before they were broken for weird reasons.  Thus "this is, obviously, dumb as hell".

"because you don't think it's your responsibility" is a very unkind reading of my words; I explained in significantly more detail why I'm not dropping my other work to spin myself up to add a pretty non-trivial new feature to WebIDL.

**Comment by bzbarsky** [comment]
> before they were broken for weird reasons

The reason is simple: people couldn't agree on what forEach() and keys() and entries() should do for them, for the non-indexed-thing case.  Specifically whether it should behave like ES Array (where did the indices come from?) or ES Set (but what if the values are not unique?).

And yes, you can specify a pair iterator, and then you can explicitly choose which of the two behaviors you want, by picking whether your keys are integers or the same as your values....

**Comment by tabatkins** [comment]
??? That doesn't match what you said above, where the conflict was about whether they should act like an array iterator (which'll just goes index-by-index, so it'll do weird things if you modify the array during iteration) vs a map/set iterator (which gets refs to the values ahead of time, so it won't change as you mutate).

The question of "does `iterator<>` make you array-like or set-like" is a completely different issue, and one with an obvious answer: uh, array-like, because `setlike<>` is for set-likes.

**Comment by bzbarsky** [comment]
The handling of removals was another point of contention, yes....  But that's part of the same thing: should it act more arraylike or setlike in terms of its iteration behavior?

**Comment by bzbarsky** [comment]
> because setlike<> is for set-likes

And to be clear, the question is what value iterators should act like when you can have repeated values and hence can't be `setlike<>`...

**Comment by tabatkins** [comment]
> And to be clear, the question is what value iterators should act like when you can have repeated values and hence can't be `setlike<>`...

Right, what I'm saying is that `iterator<>` *definitely doesn't* represent anything set-like, because `setlike<>` already does that (and you can't use them together).  It's definitely for representing array-like iterables.  Thus, there's no question of whether it should act "like a set" when iterated (for the question of what the "index" argument is for `forEach`).

Whether it should have "safe" mutation during iteration is indeed a separate question, one that *happens* to map to "is like an Array" or "is like a Map/Set", but I think there's an obvious answer there too - an `iterator<>` is a light `arraylike<>` (or subclassed Array, whatever), and so for forward-compat with possible future expansion into a full array-like, it should act like Array iterators do today.

**Comment by bzbarsky** [comment]
What's interesting is that all this is obvious to you, but wasn't to anyone else, including to the person who wrote the (now-removed) value iterator bits in webidl...

**Comment by tabatkins** [comment]
Sure, that's not uncommon. ^_^

**Comment by annevk** [comment]
This issue got side tracked a bit, but https://github.com/w3c/fxtf-drafts/issues/280 appears to be the last consumer of this feature and it can be removed there most likely as only Firefox supports it.

**Comment by annevk** [comment]
So I suggest we go ahead with removal from IDL.

**Comment by annevk** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1456887.

**Comment by dstorey** [comment]
We've just checked in removing this in Edge
