### ISSUE TITLE
Add an informative section on overloads vs. unions/optional

### ISSUE THREAD

**Issue by domenic** [heycam/webidl#307]
After I understand this better---see https://github.com/jsdom/webidl2js/issues/29#issuecomment-278347717 --- I'd like to contribute a non-normative section talking about the differences between using overloads for your APIs versus using unions/optional. Potential points to cover:

- Examples of cases that cannot be expressed in one but can in the other (or, if no such cases exist, examples where it is much easier to express in one)
- Examples of non-obvious semantic differences between an interface written using overloads vs. one written using unions/optional.
- An explanation of how the prose algorithms for the two different styles are intended to be written---i.e., overloads you should have a separate prose algorithm per overload, whereas unions/optional should have a single algorithm. It's worth adding a comment here about how overloads map well to C++ via the binding layer, and should be thought of that way; they don't as obviously map to JavaScript.
- Some small encouragement to use unions/optional instead of overloads when possible, since the spec machinery involved is much less complicated and is easier to reason about.

I'm hoping for some help on the examples; see the conversation linked to above.

**Comment by annevk** [comment]
I think we should very strongly discourage overloads. They make APIs much harder to understand.

**Comment by bzbarsky** [comment]
> They make APIs much harder to understand.

That really depends on the API.

For example, let's look at `AudioNode`.  It has this IDL at <https://webaudio.github.io/web-audio-api/#idl-def-AudioNode>:

    AudioNode connect (AudioNode destination, 
                                       optional unsigned long output = 0,
                                       optional unsigned long input = 0);
    void connect (AudioParam destination, optional unsigned long output = 0);

How would you write this without overloads?  Right now you have to do:

    any connect((AudioNode or AudioParam) destination, 
                          optional unsigned long output = 0,
                          optional unsigned long input = 0);

plus prose to explain:

1.  The third argument is ignored if the first argument is an AudioParam.
2.  The return value is an AudioNode if the first argument is an AudioNode and void otherwise.

Note that both would still be issues even if we could write `(AudioNode or void)` for the return type.

As a result, you have to go read the prose to figure out what sort of thing a call will return, etc.

Now you could make the argument that these two methods should have been called `connectNode` and `connectParam` or something.  But _if_ this was the desired API, then overloads actually express it more clearly than unions plus optional arguments would have.

Or another example, from <https://drafts.csswg.org/css-conditional-3/#the-css-interface>:

    partial interface CSS {
      static boolean supports(DOMString property, DOMString value);
      static boolean supports(DOMString conditionText);
    };

Yes, you could rewrite this as:

    partial interface CSS {
      static boolean supports(DOMString propertyOrConditionText, optional DOMString value)
    };

with prose explaining that the first arg is treated as condition text if there is no second arg, otherwise treated as a property name.  But the actual IDL is a bit more confusing this way, in my opinion.  Oh, and this would have different semantics in the case when `undefined` is passed as a second arg, which may or may not be an improvement on the current behavior; it's hard to tell.  Again, maybe these should have been different function names...

Or canvas:

    void drawImage(CanvasImageSource image, double dx, double dy);
    void drawImage(CanvasImageSource image, double dx, double dy, double dw, double dh);
    void drawImage(CanvasImageSource image, double sx, double sy, double sw, double sh, double dx, double dy, double dw, double dh);

Yes, you could do this with optionals and explicitly disallowing cases in which dw is passed but dh is not passed in the second overload.  Oh, and all the args named appropriately so they make sense for both the second and third overload.  So really, you want to disallow cases when the fourth arg is passed but no more args are passed.   Do you really think that would make the API easier to understand?  And also, also, it would still have different semantics from what we have now.

Or how about this one from `CanvasDrawPath`:

    void fill(optional CanvasWindingRule winding = "nonzero");
    void fill(Path2D path, optional CanvasWindingRule winding = "nonzero");

Try writing that with unions and then showing someone the result and asking them whether it's easier to understand than the overload version....

I stopped here; these were three of the first 5 overloads I looked at in Gecko's IDL.

**Comment by bzbarsky** [comment]
Oh, and I agree that there are overload uses that are probably somewhat silly.  Still in CanvasDrawPath, this:

    void stroke();
    void stroke(Path2D path);

can totally be written as `void stroke(optional Path2D path);` as long as you're cool with `stroke(undefined)` not throwing.

**Comment by annevk** [comment]
I think I would argue most of those cases should use different methods. Making the method signature depend on an argument just makes code hard to read.

I'll create a PR for `CanvasDrawPath`, that seems silly indeed.

**Comment by bzbarsky** [comment]
> I'll create a PR for CanvasDrawPath, that seems silly indeed.

Since that PR does change semantics, please don't forget to add a WPT!

**Comment by annevk** [comment]
I'm actually having second thoughts now since all the other methods there follow the same pattern (due to having multiple arguments). If we ever added additional arguments we'd have to change this back and then undefined not throwing might end up being problematic.

**Comment by bzbarsky** [comment]
Anyway, to answer @domenic's original question

* Examples of things that are easier to express as overloads: the fact that certain numbers of arguments are nonsensical, the fact that certain arguments are ignored or nonsensical depending on what values get passed for other arguments, return types that depend on argument types.  Yes, maybe APIs should avoid some of these things.
* Examples of things that are easier to express as unions or optionals: A function that takes three arguments, each of which can be `(Foo or Bar or Baz)` (esp if it's the same union for all three args) and all combinations are valid.  Expressing this as overloads is... bad.  Very bad.  ;)
* Non-obvious semantic differences: treating of trailing `undefined` arguments.  Unless an overload API is writte _very_ carefully it will not do this the same way trailing optionals would have.

You might want to also talk to the WebGL folks (e.g. @jdashg) about this.  I know they've though some about the difference between these options in that spec, and I seem to recall that there's currently impedance mismatch at least in Gecko between what the spec IDL says and the natural way to implement the API on the C++ side, but I don't recall the details.

**Comment by TimothyGu** [comment]
@Domenic Are you still interested in working on this? If not I'd like to take a stab at it now that @bzbarsky has provided some useful examples one could work off of.

**Comment by domenic** [comment]
Please feel free to take it over!
