### ISSUE TITLE
Example 20: spurious line in effective overload set?

### ISSUE THREAD

**Issue by dglazkov** [heycam/webidl#327]
Looking over the example, I am not sure how this line is generated by the algorithm:
` <f2, (Node, DOMString, double, double), (required, required, variadic, variadic)>,`

**Comment by bzbarsky** [comment]
Stepping through the https://heycam.github.io/webidl/#dfn-effective-overload-set algorithm:

1. S is empty set.
2. F is the set of our operations.
3. maxarg is 4 (due to the f4 overload), though in practice this will turn out to not matter.
4. m is 4 (because both maxarg and N are 4).
5. We will now consider f2.
5.1. n is 3.
5.2. (t0, t1, t2) is (Node, DOMString, double)
5.3 (o0, 01, 02) is (required, required, variadic)
5.4 Add the tuple of those two things to the overload set.
5.5 f2 is declared variadic, so:
5.5.1. for 3 <= i <= 4 add more things

and specifically, when i == 4, we add `<f2, (Node, DOMString, double, double), (required, required, variadic, variadic)>`.

**Comment by dglazkov** [comment]
Thanks, @bzbarsky!

**Comment by bzbarsky** [comment]
No problem.  ;)

Note that conceptually this _has_ to work, since the whole purpose of a variadic is to pass however many args actually got passed in.  So if it did not work, that would be a bug in the algorithm, not the example.
