### ISSUE TITLE
Separate value iterators from indexed getters

### ISSUE THREAD

**Issue by annevk** [heycam/webidl#338]
1. I'm still assuming we don't want folks to be using indexed getters as they end up creating proxies when implemented in JavaScript. TC39 told us this was less than ideal ages ago and there's no real need to revisit this I think. (The continued lack of not being able to subclass arrays is somewhat problematic here, but hasn't materialized much thus far.)
2. At the end of #291 @tabatkins indicated that for CSS they don't necessarily need indexed getters, but really would like value iterators and explained how that could work if we separated them from requiring indexed getters.

So I suggest we decouple value iterators from indexed getters, to avoid spreading indexed getters further, while still giving CSS nice APIs.

**Comment by bzbarsky** [comment]
Still, as before, requires defining what the actual behavior of things like forEach and the actual iteration should be.  Coupling to indexed getters allowed us to free-ride on the Array bits from ES.

cc @domenic

**Comment by tabatkins** [comment]
+1. Subclassing arrays would be *ideal* for [CSSUnparsedValue](https://drafts.css-houdini.org/css-typed-om/#unparsedvalue-objects) and [CSSTransformValue](https://drafts.css-houdini.org/css-typed-om/#transformvalue-objects), which are both dead (UA doesn't modify them after creation, user mutation has no special effect) lists, but have additional properties that preclude just making them bare Arrays.  Making them at least iterable is a "good enough" solution; at least then authors can do:

```js
let arr = [...cssomThing];
mutateArr(arr);
let newCssomThing = new CSSUnparsedValue(arr);
```

Less good than just `mutateArr(cssomThing)`, but hey, *it works*.

> Still, as before, requires defining what the actual behavior of things like forEach and the actual iteration should be. Coupling to indexed getters allowed us to free-ride on the Array bits from ES.

You just... define them the same way. (Specifically: forEach's callback arguments are (element, index, collection) like Array.forEach, not (element, element, collection) like Set.forEach; iteration is "live" and run by just iterating an index over the collection, so mutation in the loop interacts with iteration, rather than making a copy and iterating over that.)

Context: in <https://github.com/heycam/webidl/issues/291#issuecomment-284897010> Boris said one of the original problems with value iterators was disagreement on whether they should iterate like Sets or Arrays. Since people seemed to be okay with "uh, just free-ride on Arrays" as an answer, I'm not sure what the problem is - you make them act like an Array.

**Comment by tobie** [comment]
That's a dup of #325, right?
