### ISSUE TITLE
Given [Constructor, Constructor(DOMString x)], new C(undefined) picks the second

### ISSUE THREAD

**Issue by domenic** [heycam/webidl#351]
In particular by my reading the overload resolution algorithm, the step

> Remove from S all entries whose type list is not of length argcount.

immediately disqualifies the no-arg constructor from consideration.

This seems not so great. Can we "trim trailing undefineds" before invoking the overload resolution algorithm?

/cc @bzbarsky

This is concretely an issue for [DOMMatrix](https://drafts.fxtf.org/geometry/#dommatrix).

**Comment by foolip** [comment]
This behavior was deliberately used with `alert()` + `alert(DOMString message)` in https://github.com/whatwg/html/commit/0b570cf14d1ac33d7e7854114342ebd8c8ea624f.

Here Blink's IDL now [matches the spec](https://chromium.googlesource.com/chromium/src/+/784a562a06cb594ee8164fc191017529270988c3), but there are [other cases](https://bugs.chromium.org/p/chromium/issues/detail?id=701539) of optional vs. override mismatches that might be observable. @mdittmer, would you be able to interrogate your dataset to find all such cases?

I think that to just "trim trailing undefineds" wouldn't work, certainly if `foo(DOMString x)` is the only signature, then `foo(undefined)` shouldn't throw because of too few arguments. Maybe it would work to drop trailing undefineds down to the minimum number of arguments in any override, but I'm not sure.

**Comment by annevk** [comment]
Yeah, this design is also deliberately used by XMLHttpRequest's open(). Avoid overloads if you don't want weird cases and use unions and optional instead.

**Comment by bzbarsky** [comment]
As previously mentioned, this is very much by design: overloads discriminate on argc first, and there are specs that depend on that.  If DOMMatrix wants to treat undefined first arg as no args, it should be doing:

    Constructor(optional DOMString transformList)

(or `Constructor(optional sequence<unrestricted double> numberSequence)`) and then handling the "not present" case.

**Comment by annevk** [comment]
It seems they could just have `Constructor(optional (DOMString or sequence<unrestricted double>) init = [])` or some such.

**Comment by bzbarsky** [comment]
Yes, that would be an option as well, with an extra case for "sequence has 0 elements" at https://drafts.fxtf.org/geometry/#dom-dommatrix-dommatrix-numbersequence

**Comment by bzbarsky** [comment]
That depends on whether you want to allow `new DOMMatrix([])` with an explicit empty array.

**Comment by annevk** [comment]
Fair, "" is better than as they already handle that.

**Comment by bzbarsky** [comment]
There was talk of not exposing the string signature in workers, but exposing the rest, so whether to use `""` depends on that a bit.

**Comment by foolip** [comment]
> @mdittmer, would you be able to interrogate your dataset to find all such cases?

Mark helped me out with this offline, and among the candidates no other problematic cases were found. It didn't include constructors though, so there might be more like DOMMatrix waiting to be discovered.
