### ISSUE TITLE
Should ReadOnlyMember use ReadOnly?

### ISSUE THREAD

**Issue by annevk** [heycam/webidl#399]
Not sure it matters, but it seems slightly weird to define the keyword twice.

**Comment by tobie** [comment]
So `ReadOnly` is actually `"readonly" or ε`, so that wouldn't work.

**Comment by annevk** [comment]
Ah, so we do have AttributeNameKeyword for a single keyword that's not even reused but we don't have ReadOnlyKeyword for a keyword that is reused. I really don't understand the principles behind this grammar.

**Comment by tobie** [comment]
I don't think that's the result of principles, just the outcome of a number of changes. Needs a cleanup at some point.

**Comment by tobie** [comment]
So having looked at this a little more: `ReadOnly` is really `OptionalReadOnly`. Maybe we should actually use the `Optional` prefix consistently throughout the grammar.

`AttributeNameKeyword` is the weirdest thing ever. I have no idea what the `"required"` terminal is doing in there. And it predates the switch to Bikeshed.

**Comment by bzbarsky** [comment]
> I have no idea what the "required" terminal is doing in there.

Poking at archive.org, the last pre-bikeshed version it has is https://web.archive.org/web/20160906235942/https://heycam.github.io/webidl/ and that has this grammar:

[43] AttributeName → AttributeNameKeyword | identifier

That is, an attribute name can be any identifier, or "required" (which is a keyword in the grammar, as of required things in dictionaries, hence not an identifier).  In other words, "attribute boolean required;" is valid IDL.

I _think_ the post-bikeshed grammar is equivalent but a bit less obvious, because it doesn't make alternation quite as clear (uses whitespace, not an explicit '|' to indicate it).

In any case, AttributeNameKeyword exists as a thing, as opposed to just having "required" as an alternation in AttributeName so that if we add any more keywords to IDL we'll add them to AttributeNameKeyword and not break existing uses of attributes with those names.  Though we _could_ just directly add things to AttributeName, I guess.  Either way.

**Comment by tobie** [comment]
> That is, an attribute name can be any identifier, or "required" (which is a keyword in the grammar, as of required things in dictionaries, hence not an identifier). In other words, "attribute boolean required;" is valid IDL.

That was my understanding too. But I'm still confused as to what that would mean, though, or why we even have it?

> I think the post-bikeshed grammar is equivalent but a bit less obvious, because it doesn't make alternation quite as clear (uses whitespace, not an explicit '|' to indicate it).

Yeah. It's modeled after the ES one.

**Comment by bzbarsky** [comment]
> But I'm still confused as to what that would mean, though, or why we even have it?

Why what would mean?

**Comment by bzbarsky** [comment]
> But I'm still confused as to what that would mean, though

It would mean an attribute named "required".  Like the one HTMLInputElement, HTMLTextAreaElement, HTMLSelectElement have.

**Comment by tobie** [comment]
OK, so bz explained this to me. It's due to keywords having precedence over identifiers.
