### ISSUE TITLE
Unexplained restrictions in operation bindings section

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#511]
The [first sentence of the Operation bindings section](https://heycam.github.io/webidl/#es-operations) reads (empahsis mine):

> For each unique identifier of an exposed operation defined on the interface, there must exist a corresponding property, *unless the effective overload set for that identifier and operation and with an argument count of 0 has no entries.*

I'm unsure what the intent of the emphasized part of that sentence is. Are there existing APIs that end-up not being exposed because of this clause, and if so, why should they?

Will document this via a note so future me doesn't get confused again.

Tagging @heycam, @bzbarsky, and @domenic. Thanks in advance for your help.

**Comment by bzbarsky** [comment]
I also can't tell what this clause is trying to get at...

**Comment by TimothyGu** [comment]
In fact, there cannot be a case where the effective overload set for an identifier of an operation is empty, because of step 5.6 in the algorithm to compute the effective overload set, which is always executed if an operation with that identifier exists.

Historically however, it seems that there can be some cases where the effective overload set *can* be empty, due to a feature called "omittable special operations" (see [snapshot](https://rawgit.com/heycam/webidl/b825a6a50e4e78ad2e4f17272d1575115e231241/Overview.html#idl-operation-overloading) taken at b825a6a50e4e78ad2e4f17272d1575115e231241, steps 3-5).

This seems like sufficient grounds for removal of this this condition.

**Comment by tobie** [comment]
So "unless the effective overload set for that identifier and operation has no entries" was added in https://github.com/heycam/webidl/commit/dea306ae4720ac800c4a054de1b8533140cf4f32. (The "argument count of 0" bit was introduced in https://github.com/heycam/webidl/commit/8e66595d495b40d05c9926fbd01b0fa0be5ecb6a.) It looks related to the now defunct `[OmitIndexingProperties]` extended attribute (as a means of removing said properties?), so it seems we should be able to just get rid of it, no?

**Comment by TimothyGu** [comment]
@tobie [OmitIndexingProperties] was immediately renamed to [NoIndexingProperties] in the next commit, and to "omittable special operations" (which I referred to in https://github.com/heycam/webidl/issues/511#issuecomment-357052546) to account for other special operations some time later.

> so it seems we should be able to just get rid of it, no?

Yes.

**Comment by tobie** [comment]
> [OmitIndexingProperties] was immediately renamed to [NoIndexingProperties] in the next commit, and to "omittable special operations" (which I referred to in #511 (comment)) to account for other special operations some time later.

Yeah, sorry, I hadn't seen your comment before posting mine.

**Comment by Ms2ger** [comment]
This seems to have been fixed at some point.
