### ISSUE TITLE
Should an @@unscopables property also be defined for globals?

### ISSUE THREAD

**Issue by tobie** [heycam/webidl#544]

**Comment by ExE-Boss** [comment]
What&nbsp;would this&nbsp;do?

Can&nbsp;you&nbsp;provide&nbsp;reasoning as&nbsp;to&nbsp;why&nbsp;we&nbsp;might want&nbsp;to&nbsp;do or&nbsp;not&nbsp;do&nbsp;this?

**Comment by annevk** [comment]
It was a question in #494. I don't think there's a need for this and in general we haven't really used unscopables much.

**Comment by bathos** [comment]
The spec still links to this issue in a note at [step 10 of “create an interface prototype object”](https://webidl.spec.whatwg.org/#create-an-interface-prototype-object):

> _Should an @@unscopables property also be defined if interface is declared with the [Global] extended attribute? This is discussed in issue #544._

The “also be” in the note is maybe misleading because the steps which follow it _do_ define @@unscopables properties on interface prototype objects for [Global] interfaces if they have [Unscopable] members. AFAICT there just aren’t any qualifying interfaces being defined out there in practice.

Maybe the note should be removed now? It seems pretty harmless that it’s presently permitted, but if it were desirable to expressly forbid it, the place to do that wouldn’t be in those steps anyway — it’d be in the definition of [[Unscopable]](https://webidl.spec.whatwg.org/#Unscopable) (e.g. “[Unscopable] must not be declared on members of [Global] interfaces” etc).
