### ISSUE TITLE
DOMException function definition makes no sense

### ISSUE THREAD

**Issue by bzbarsky** [heycam/webidl#55]
@domenic, how does http://heycam.github.io/webidl/#es-DOMException-call actually produce a DOMException instance?  It's delegating to Construct() on its proto, which is %Error%, which certainly won't produce the right sort of object if the intent is to produce a "platform object".  They need the right branding, etc.

**Comment by foolip** [comment]
Perhaps the spec should just define DOMException in terms of Web IDL, as that's how it's implemented in both Gecko and Blink?

**Comment by domenic** [comment]
The intent is not to produce a platform object. The intent is to just produce a normal Error subclass, like TypeError etc.

**Comment by bzbarsky** [comment]
> The intent is not to produce a platform object

DOMException is explicitly defined and treated as a platform object throughout the rest of Web IDL.  There is no way to implement the other requirements Web IDL places on DOMException if it's not a platform object.  So either all the rest of the DOMException handling in the spec needs to be changed, or this constructor needs to create the right sort of object.

I should note that currently UAs implement DOMException as a platform object, and it's not obvious that changing that would necessarily be web-compatible.  If we think the gain is sufficiently worth it we _could_ try changing all UAs here, of course, but this is very much not the normal paving of cowpaths we normally use for decades-old functionality.

**Comment by domenic** [comment]
> DOMException is explicitly defined and treated as a platform object throughout the rest of Web IDL.

OK, I believe you, but could you point out an example or two? E.g. I was under the impression it's not a Web IDL type, so you can't e.g. accept it as a type and base overload resolution on it.

**Comment by domenic** [comment]
OK, looking at the spec at least I can see that I am confused. Still curious if there are any easy examples of where this shows up in practice, but yeah, I need to think about this more...

**Comment by travisleithead** [comment]
FWIW: in Edge (and IE since IE9) this has been implemented as an interface:

```webidl
interface DOMException
    {
        const unsigned short INDEX_SIZE_ERR = 1;
        // [snip]

        readonly attribute unsigned short code;
        stringifier readonly attribute DOMString message;
        readonly attribute DOMString name;
    };
```

**Comment by bzbarsky** [comment]
@domenic You were under an incorect impression, as you noticed.  In practice, nothing accepts a DOMException argument to a method or setter yet, so maybe we can rip all that stuff out.  My point is just that right now the spec is totally inconsistent, and people are trying to use DOMExeception in more cases (e.g. as attribute values), so we should get things sorted out before someone _does_ introduce DOMException arguments somewhere.

**Comment by domenic** [comment]
Right, agreed the spec as-is is inconsistent.

The question then is whether we'd want to:

1. Change the parts of the spec that treat DOMException as a platform object, in favor of treating it like the spec treats other Error types; or
2. Just treat it as an `interface`, probably similar to @travisleithead's but with a [Constructor], and then let all that fall out automatically.

(2) is certainly easier and has the advantage of matching ~3 browsers. Whereas (1) gives platform consistency. It seems like implementers are going to favor (2) so it might be best to just admit defeat on consistency here, but I'd like to think about this a bit more before saying that for sure.

**Comment by domenic** [comment]
Actually, in terms of implementations, how does the wiring currently work for inheriting from Error? E.g.:

- @travisleithead's definition seems like it doesn't inherit at all.
- Do Chrome and Firefox do prototype-side inheritance?
- Do they do class-side inheritance?
- Do they do super-calls for object allocation, so that [[ErrorData]] is set? (Concrete test: `Object.prototype.toString.call(aDomException)` should give `[object Error]`, like it does for `TypeError` etc.)

**Comment by bzbarsky** [comment]
The current Gecko setup is that `DOMException.__proto__ == Function.prototype` and `DOMException.prototype.__proto__ == Error.prototype`.  We don't really implement supercall at all yet, so the supercall question is a bit fishy, but the brand we use internally for Object.prototype.toString is set to "DOMException" for `DOMException` instances, like it is for other IDL interfaces.

**Comment by travisleithead** [comment]
Edge is similar except that ```DOMException.prototype.__proto__ == Object.prototype``` (we have a bug filed to change this to inherit from ```Error.prototype```).

**Comment by foolip** [comment]
Apparently, `DOMException.prototype.__proto__ === Error.prototype` in Blink, but it doesn't show in the IDL or C++, it's probably some special handling of `DOMException` in the bindings generator.

**Comment by domenic** [comment]
OK. So, concretely, here are our two options, in terms of actual work:

1. Stay the course on consistifying DOMException with the rest of the platform's Error subclasses.
   - Probably best to update Web IDL to subsume the treatment of DOMException into that of Error, instead of having it as a distinct type. Since it calls super(), it has an [[ErrorData]], and can thus be treated entirely equivalently. And it doesn't have any extra branding data that could be used to distinguish.
   - All specs that reference the DOMException type would then be updated to reference the Error type. As far as I can tell this is only used for getters, callback params, and return values, so this should not change any normative behavior.
   - Implementers would need to make the relevant changes. In particular their binding code would need to have a custom Error subclass, implemented similar to TypeError or Promise, and then wired into the bindings code in the same way.
2. Give up on this and re-use existing Web IDL mechanisms.
    - The fact that we want the prototype to be Error.prototype (and probably we want class-side inheritance as well, i.e. `DOMException.__proto__ === Error`) means there needs to be *some* special code. We can't use `interface` or `: Error` directly.
    - IIRC old-Web IDL had an `exception` construct which was similar to `interface` in this way but had that special wiring. That might also be useful for stuff like https://github.com/w3c/mediacapture-main/issues/162
    - Bindings generators would presumably need to implement such a construct. It sounds like Blink and Gecko do already, in one form or another.
    - Once we have that construct we use it to define `DOMException` in Web IDL like other platform objects. No need for this "DOMException constructor object" or "DOMException prototype object" structure.

The delta between the two in terms of web-observable changes would be that:
- (1) has writable own-data properties for `code`, `name`, and `message`; (2) has proto-getters.
- (1) can be constructed without `new`, like other Error subclasses; (2) cannot.
- (1) has `Object.prototype.toString.call(de)` returning `"[object Error]"`, like other `Error` subclasses; (2) has it returning `"[object DOMException]"`.

Given the comparison between the amount of work involved here, it's hard for me to continue supporting (1). Especially since all of the deltas could in theory be addressed by extensions to Web IDL. So, I acede.

Can I turn over the work of making a spec-patch for (2) to someone else? Or is it my responsibility, as penance for introduce a nonsensical situation in the first place? ;) I'm especially unsure about the `exception` vs. `interface` construct and how we would do that.

**Comment by Ms2ger** [comment]
@domenic seems like this is on you :)

I don't think there's any point in reintroducing the `exception` construct.

**Comment by domenic** [comment]
OK, this finally came back to bite us, as Chrome noticed they were incompatible with the current spec and started working to update themselves. That's not great, as currently browsers mostly agree with each other and disagree with the current spec.

To be sure, I created new tests at https://github.com/w3c/web-platform-tests/pull/6361. Indeed, everyone still fails them.

I will work on fixing the spec. I have one big question though: Given that we need to inherit from `Error`, should we:

- Use `interface`, `[Constructor]`, etc. but add an additional requirement about the exotic bindings?
- Or define the object from scratch, since it doesn't follow the usual rules for interfaces?

I am leaning toward the first.

**Comment by bzbarsky** [comment]
My gut feeling is we should do the first.  Gecko has an `[ExceptionClass]` thing which is like `[ArrayClass]` in terms of how it sets up the inheritance, but with `Error` instead of `Array`.   I agree it's a bit odd to add such a thing for this one use case, of course....

**Comment by domenic** [comment]
Yeah, I think a one-off sentence is better than inventing a new extended attribute, although of course implementations might implement it that way.

I've posted a PR. However I also discovered that Safari seems to have aligned with the spec on own-ness of the properties, interestingly.
