### ISSUE TITLE
Add dedicated IDL syntax for indexed property getters

### ISSUE THREAD

**Issue by inexorabletash** [heycam/webidl#584]
https://github.com/w3ctag/design-reviews/issues/229#issuecomment-424390065 -

> It took some doing, but we eventually discovered that it’s possible to iterate over the NamedNodeMap using for..of, but we had to discover this through an obscure part of WebIDL. Would be nice if this could be made more obvious? E.g., an @@iterator directive..

Specifically: https://heycam.github.io/webidl/#es-iterator - an interface with an indexed property getter and an integer-typed length attribute gets @@iterator applied.

This is subtle enough in the spec that it comes up frequently, e.g. as feature requests for specs that already support it. I'm guilty of missing it at least once myself and filing a bug.

One approach would be to simply have it be best practice for spec authors to annotate their WebIDL:

```webidl
  readonly attribute unsigned long length;
  getter Attr? item(unsigned long index);
  // @@iterator is implicitly provided c/o the above attribute/getter
```

Alternately, we could invent a WebIDL syntax for this, e.g.

```webidl
  indexedIterable<Attr>;
```
... which desugars into the above, requiring the same prose. But then a `setter` (if any) looks weird.

**Comment by bzbarsky** [comment]
Not  all indexed getters are named "item" (some are anonymous, some are getItem).  So the desugaring would need to be parametrized on more things.

There's a tradeoff here between spec authoring and spec reading.  We _could_ add a requirement that any time you have an indexed getter and length you need to include some other syntactic construct which makes it clear you're iterable.  But since most spec authors don't run their IDL through any IDL-validity tooling, afaict, it would be easy to forget this construct and end up with invalid IDL.

For extra confusion, you can already add `iterable<Attr>` to something like `NamedNodeMap`.  It doesn't change what happens with `@@iterator` but does expose more methods like `entries`, `forEach`, `keys`, `values`.

**Comment by domenic** [comment]
I would suggest better documentation in domintro boxes. Making Web IDL more readable for humans is a worthy goal, but I don't think it should lead to adding redundant constructs that need to be kept in sync with each other. Ideally the humans should be reading the domintro boxes instead.
