### ISSUE TITLE
Grammar does not allow non-readonly regular attributes in mixin

### ISSUE THREAD

**Issue by peria** [heycam/webidl#702]
In [interface mixin](https://heycam.github.io/webidl/#idl-interface-mixins) section, we enumerate [regular attributes](https://heycam.github.io/webidl/#dfn-regular-attribute) in *MixinMember*.
In [grammar](https://heycam.github.io/webidl/#idl-grammar) chapter, on the other hand, it does not allow [*ReadWriteAttribute*](https://heycam.github.io/webidl/#index-prod-ReadWriteAttribute), which is a kind of regular attribute, as a member of [*MixinMember*](https://heycam.github.io/webidl/#index-prod-MixinMember).

**Comment by bzbarsky** [comment]
This is a little subtle.  There are four ways you can write an attribute declaration:
```
  inherit attribute type name;
  readonly attribute type name;
  attribute type name;
```
Interfaces and partial interfaces allow all four types.  The first one is allowed by this production under [_ReadWriteAttribute_](https://heycam.github.io/webidl/#prod-ReadWriteAttribute) (which is one of the options under [_InterfaceMember_](https://heycam.github.io/webidl/#prod-InterfaceMember)):
```
    inherit ReadOnly AttributeRest
```
The second one is allowed by having [_ReadOnlyMember_](https://heycam.github.io/webidl/#prod-ReadOnlyMember) in [_InterfaceMember_](https://heycam.github.io/webidl/#prod-InterfaceMember).  [_ReadOnlyMember_](https://heycam.github.io/webidl/#prod-ReadOnlyMember) then allows readonly attributes via [_ReadOnlyMemberRest_](https://heycam.github.io/webidl/#prod-ReadOnlyMemberRest) allowing [_AttributeRest_](https://heycam.github.io/webidl/#prod-AttributeRest).  Finally, the third one is allowed by [_ReadWriteAttribute_](https://heycam.github.io/webidl/#prod-ReadWriteAttribute) including _AttributeRest_ directly.

On the other hand, mixins only allow the second and third option, by having
```
    ReadOnly AttributeRest
```
under _MixinMember_.  Note that the [_ReadOnly_](https://heycam.github.io/webidl/#prod-ReadOnly) production allows either the keyword "readonly" or nothing at all, so that grammar allows both readonly and writable attributes.  This is explicitly called out in the [list of productions that attributes can match](https://heycam.github.io/webidl/#idl-attributes).

So mixins do in fact allow non-readonly regular attributes.  What they don't allow is the use of the "inherit" keyword on them, because that doesn't make much sense: you can't define an attribute getter to "do what the thing we inherit from does" if you have no idea what you're inheriting from!

The grammar does technically allow `inherit readonly attribute type name;` but the prose for the "inherit" bit explicitly says:

> inherit must not appear on a read only attribute or a static attribute

so that would not be valid IDL.  It might be nice to adjust the grammar to disallow it, though, by removing the _ReadOnly_ bit from that branch of _ReadWriteAttribute_.  I filed https://github.com/heycam/webidl/issues/703 on that.

Closing, because I think this issue as filed is not an issue.

**Comment by peria** [comment]
Thank you for the clarification. It makes sense. I misunderstood that _ReadOnly_ did not allow ε.
