### ISSUE TITLE
Does WebIDL define whether or not the interface constructor should be exposed on the global?

### ISSUE THREAD

**Issue by timdream** [heycam/webidl#820]
Here is something I observed on modern browsers

Navigator:

```
> window.Navigator
< function Navigator() {
      [native code]
  }
> window.navigator
< Navigator {...}
> window.navigator instanceof window.Navigator
< true
> window.navigator.constructor === window.navigator
< false
> Navigator.prototype === navigator.constructor.prototype
< true
```

Geolocation (Chrome):

```
> navigator.geolocation
< Geolocation {...}
> navigator.geolocation.constructor
< function Geolocation() {
      [native code]
  }
> window.Geolocation
< undefined
```

Geolocation (Safari and Firefox):

```
> navigator.geolocation.constructor
< function Object() {
      [native code]
  }
< navigator.geolocation.constructor === Object
> true
```

There are a few issues here:

1. Constructors are not available on the global (`window`). When I look up the WebIDLs of these interfaces, I don't see there are being defined differently. They are both defined with `[Exposed=Window]` extended attribute. Isn't this what `Exposed` do — to make the constructor available on `window`?
2. In Chrome's case for `navigator`, `<instance>.constructor` seems to point to different version of that, even when `<instance>.constructor.prototype` is pointing to the same object. Is this a bug in the implementation, or something not defined in WebIDL?
3. In Safari & Firefox's case, `Geolocation` constructor is not exposed, and `navigator.geolocation.constructor` simply gives me the `Object` constructor. Is this a bug in the implementation, or something not defined in WebIDL?

Use case:

The `Navigator` and `Geolocation` constructors are bad examples — they are not useful. But for instances of objects that can only be accessed via a callback, for example, `GeolocationCoordinates`, having access to `GeolocationCoordinates.prototype` allow me to look at the available properties without invoke a geolocation request.

Let me know if I should file an issue to browsers or redirect the issue to other spec. Thanks.

**Comment by bathos** [comment]
[`[Exposed]`](https://heycam.github.io/webidl/#Exposed) describes the ‘exposure set’ of an interface. Its value is one or more identifiers of interfaces that have the [`[Global]`](https://heycam.github.io/webidl/#Global) extended attribute — e.g. `Window`, `Worklet`, etc.

If the exposure set of an interface is `Window`, this means the interface exists in realms whose global object is `Window`, but not otherwise. By default, when exposed, it does also mean that the constructor will be made available as a property of the global object whose key is the name of the interface. But another extended attribute, [`[NoInterfaceObject]`](https://heycam.github.io/webidl/#NoInterfaceObject), modifies that behavior: it makes it so that the constructor does not appear as a global property. The example you gave, `Geolocation`, uses `[NoInterfaceObject]`, which is why a global property isn’t created for its constructor.

Whether to create a property is a distinct concept from exposure. The interface object and its instances cannot exist at all in a realm whose global object is not in its exposure set.

New interfaces aren’t meant to use `[NoInterfaceObject]`. It’s around for legacy reasons.

>  Chrome's case for navigator, <instance>.constructor seems to point to different version of that, even when <instance>.constructor.prototype is pointing to the same object. Is this a bug in the implementation, or something not defined in WebIDL?

I believe there is just a typo in your test here. You wrote `window.navigator.constructor === window.navigator` instead of `window.navigator.constructor === window.Navigator`.

**Comment by bzbarsky** [comment]
> When I look up the WebIDLs of these interfaces, I don't see there are being defined differently

`Geolocation` used to be `[NoInterfaceObject]` in the Geolocation spec and in implementations. The spec got changed, but implementations have largely not followed (though Chrome dev _does_ have a `window.Geolocation`, fwiw; I'm not sure which version of Chrome you tested and whether their change is channel-limited or just recent: I don't see `window.Geolocation` in Chrome release 78, but do see it in Chrome beta 79).

> Isn't this what Exposed do — to make the constructor available on window?

Exposed says where things might be available, yes.  They won't be available where they are not exposed, but might be unavailable even in places where they are exposed (e.g. `[Exposed=Window,SecureContext]` is exposed only on some windows).

> In Chrome's case for navigator, `<instance>.constructor` seems to point to different version of that

I'm not sure what you mean.  `navigator.constructor` should be the same object as `window.Navigator`, and is in all browsers.  What are you really asking about here?

> In Safari & Firefox's case, Geolocation constructor is not exposed, and navigator.geolocation.constructor simply gives me the Object constructor.

This is correct behavior for a `[NoInterfaceObject]` interface.  See https://heycam.github.io/webidl/#interface-prototype-object step 12: since that step doesn't define anything, you get `Object.prototype.constructor`.

There's no Web IDL issue here, as far as I can tell.

**Comment by timdream** [comment]
Thanks for the quick replies. I should have been more careful when comparing the spec and the implementation versions. Geolocation interfaces was literally changed [two days ago](https://bugzilla.mozilla.org/show_bug.cgi?id=1575144)... I can observe the correct and expected behavior on Nightly.
