### ISSUE TITLE
The specific type of any (general question)

### ISSUE THREAD

**Issue by bathos** [heycam/webidl#823]
([2.13.1](https://heycam.github.io/webidl/#idl-any))

> The any type is like a discriminated union type, in that each of its values has a specific non-any type associated with it. For example, one value of the any type is the unsigned long 150, while another is the long 150. These are distinct values.
>
> The particular type of an any value is known as its specific type. (Values of union types also have specific types.)

My understanding of _any_ had been that values of this type were only apt to be created when consuming external input. The spec gives the examples "unsigned long 150" and "long 150" for possible specific types/values, though, which suggests I might have the wrong idea about it since neither of these specific types are ones which could have resulted from converting an ES value.

(It’s also a bit confusing that it’s defined as “the union of all other possible non-union types,” since _unsigned long_ and _long_ can’t coexist in a union.)

Could anybody clarify the intended scope / usage of _any?_ Are there existing examples where it gets used with specific types other than the handful that can be produced during [ES value conversion](https://heycam.github.io/webidl/#es-any)?

**Comment by bzbarsky** [comment]
Any time `any` is used as a return value, the underlying algorithm could create the IDL `any` value from any type of IDL value, right?  When the `any` is then converted to an ES value, the specific rules for the type of IDL value it was created from would need to be applied.

As a specific example, `CustomElementRegistry.prototype.get` sometimes returns a `Function` instance (which is not one of the types https://heycam.github.io/webidl/#es-to-any produces, note) and sometimes returns undefined.  

Now there are definitely some specs that seem to think that `any` means "an ES value".  The `IDBCursor.prototype.key` getter certainly seems to think that...

On the other hand, the `IDBObjectStore.prototype.keyPath` getter does the expected thing and treats `any` as a union of IDL values; in this case it assigns either a `DOMString` of a `sequence<DOMString>` to it... but of course that's actually wrong, because it should be returning the same thing each time in the sequence case, so the spec steps there are kinda wrong and you have to ignore them and do something else.  :(

Most places that use `any` either pass it through as opaque or do ES-to-IDL conversions, of course.

> (It’s also a bit confusing that it’s defined as “the union of all other possible non-union types,” since unsigned long and long can’t coexist in a union.)

That's union in the sense of general CS concepts, not an IDL union type.  I mean an `any` can also be any interface type, even though some interface types are not distinguishable.

**Comment by bathos** [comment]
Thanks for the explanation — makes sense!
