### ISSUE TITLE
Allow ES2020 BigInt values to be passed to operations taking integers.

### ISSUE THREAD

**Issue by ExE-Boss** [heycam/webidl#828]
**ES2020**&nbsp;adds the&nbsp;`BigInt`&nbsp;type, which&nbsp;allows for&nbsp;integers&nbsp;outside the&nbsp;<code>‑2<sup>53</sup>...2<sup>53</sup>&nbsp;‑&nbsp;1</code> to&nbsp;be&nbsp;represented in&nbsp;**JavaScript**&nbsp;code.

This&nbsp;makes it&nbsp;possible to&nbsp;handle the&nbsp;full&nbsp;range of&nbsp;<code>long&nbsp;long</code> and&nbsp;<code>unsigned&nbsp;long&nbsp;long</code> values&nbsp;in&nbsp;**JavaScript**.

**Comment by bzbarsky** [comment]
Please see https://github.com/heycam/webidl/pull/525

**Comment by bzbarsky** [comment]
And in particular, the decision there was that BigInt will be a separate type not passable to operations taking integers, for consistency with ES.

I assume you meant `long long` and `unsigned long long`, by the way, since the full range of `long` and `unsigned long` is not a problem in the ES bindings.

**Comment by ExE-Boss** [comment]
Yeah, I&nbsp;keep&nbsp;mistakenly&nbsp;thinking of&nbsp;the&nbsp;**Java**&nbsp;`long`&nbsp;type, which&nbsp;is&nbsp;an&nbsp;`i64`, whereas&nbsp;**WebIDL**&nbsp;uses the&nbsp;**C**&nbsp;`long`, which&nbsp;is&nbsp;an&nbsp;`i32`.

I&nbsp;suggest we&nbsp;rename&nbsp;them to&nbsp;remove this&nbsp;confusion: <https://github.com/heycam/webidl/issues/843>.

**Comment by annevk** [comment]
Let's dupe this into that PR.
